[package]
name = "rs-util-github-release"
version = "0.1.0"

description = '''
Creates Github releases
and uploads artifacts.'''

edition = "2021"

[dependencies]
clap = { version = "4.5.30", features = ["derive"] }
