name: bash-util-github-release

on:
  push

jobs:
  build-and-release:
    name: build and release
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3.5.3

      - name: create some release artifacts
        run: |
          mkdir ./dist
          touch ./dist/file1.zip
          touch ./dist/file2.exe
          dir ./dist

      - name: create release and upload artifacts
        run: ./github-release.sh
        env:
          GH_TOKEN: ${{ github.token }}
