name: rs-util-github-release

on:
  push

jobs:
  build-and-release:
    name: build and release
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3.5.3

      - name: build
        run: printenv | sort
