name: rs-util-github-release

on:
  push

jobs:
  build-and-release:
    name: build and release
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3.5.3

      - name: gh status
        run: |
          gh auth status
          VERSION="v$(grep -E '^version = "(.+)"' Cargo.toml | sed 's/.\+"\(.\+\)"/\1/')"
          gh release create "$VERSION"
        env:
          GH_TOKEN: ${{ github.token }}
